### ISSUE TITLE
Broken Number::NewRelic source

### ISSUE THREAD

**Issue by jamestyj** [fdietz/team_dashboard#78]
Backtrace after adding NewRelic widget:

```
Internal Server Error: #<NameError: uninitialized constant Sources::Number::NewRelic::NewRelicConnection::NewRelicApi> 
/home/jamestyj/code/dashboard/app/models/sources/number/new_relic.rb:33:in `account'
/home/jamestyj/code/dashboard/app/models/sources/number/new_relic.rb:38:in `application'
/home/jamestyj/code/dashboard/app/models/sources/number/new_relic.rb:42:in `threshold_value'
/home/jamestyj/code/dashboard/app/models/sources/number/new_relic.rb:59:in `get'
/home/jamestyj/code/dashboard/app/controllers/api/data_sources_controller.rb:6:in `index'
```

Looking at `app/models/sources/number/new_relic.rb:33`:

``` ruby
def account
  NewRelicApi.api_key = api_key
  @account ||= NewRelicApi::Account.find(:first)
end
```

Grepping the source tree reveals that `NewRelicApi` is never defined. From the commit history, it looks like the file was overlooked during the migration in commit d812551f84fc69a0d6bc5228ef38bb498117bb55?

**Comment by fdietz** [comment]
Thanks! The gem was missing.
